services:
  db:
    image: postgres:13
    container_name: stores_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - store-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "stores", "-h", "stores_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build: .
    container_name: stores_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}  
      DB_PORT: ${DB_PORT}  
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}  
    networks:
      - store-network
    command: ["node", "backend/server.js"]

  frontend:
    build: ./public
    container_name: stores_frontend
    ports:
      - "3001:80"
    networks:
      - store-network
    depends_on:
      - app

networks:
  store-network:
    driver: bridge

volumes:
  pg_data:
    driver: local